# Elimination with Matrices
视频链接：https://www.youtube.com/watch?v=QVKj3LADCnA

将我的笔记用md/latex公式化、numpy代码化、和plt可视化。要求用到的函数和库都需要给出使用方法的注释

两组矩阵相互点乘，一定把左边那个视为行向量，右边的视为列向量，假设左边的向量a行b列，右边的是c行d列。要使得点乘成立（有意义），必须有b=c，并且输入维度是列数（a行数据b维特征），输出维度是行数。乘积 $A \cdot B 就是一个 a \times d$ 的矩阵。

- 经典意义上的点积:   
$1 \times n 行向量 \cdot n \times 1 列向量 → 标量（scalar）$
比如我们常讲列向量作为一个权重向量。  

- 矩阵乘法（Matrix Multiplication）——是点积的推广:  
$$
	A \in \mathbb{R}^{a \times b} 是一个矩阵\\
	B \in \mathbb{R}^{b \times d} 是另一个矩阵
$$
每一个结果中的元素，就是第 i 行向量 与 第 j 列向量 的点乘结果。

点乘仅产生一个标量，矩阵乘法则会产生一整个新矩阵

In [12]:
import numpy as np

# 初始矩阵
A = np.array([
    [1, 2, 1],
    [3, 8, 1],
    [0, 4, 1]
], dtype=float)

# 第一步：R2 = R2 - 3 * R1
A[1] = A[1] - 3 * A[0]

# 第二步：R3 = R3 - 2 * R2
A[2] = A[2] - 2 * A[1]

print("消元后的矩阵：\n", A)

消元后的矩阵：
 [[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]]


📘 回带求解

💡 原始线性方程组

$$
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1 \\
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z \\
\end{bmatrix}
=
\begin{bmatrix}
2 \\
12 \\
2 \\
\end{bmatrix}
$$

🧮 增广矩阵构造

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
3 & 8 & 1 & 12 \\
0 & 4 & 1 & 2 \\
\end{array}
\right]
$$

🔁 消元过程（带右端向量）
1.	$R_2 \leftarrow R_2 - 3 \times R_1$：

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
0 & 2 & -2 & 6 \\
0 & 4 & 1 & 2 \\
\end{array}
\right]
$$

2.	$R_3 \leftarrow R_3 - 2 \times R_2$：

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
0 & 2 & -2 & 6 \\
0 & 0 & 5 & -10 \\
\end{array}
\right]
$$

⸻

🔁 回代求解：

由上三角矩阵得到：

$$
\begin{cases}
5z = -10 \Rightarrow z = -2 \\
2y - 2z = 6 \Rightarrow 2y + 4 = 6 \Rightarrow y = 1 \\
x + 2y + z = 2 \Rightarrow x + 2 -2 = 2 \Rightarrow x = 2 \\
\end{cases}
$$

In [13]:
import numpy as np

# 系数矩阵 A 和右端项 b
A = np.array([[1, 2, 1],
              [3, 8, 1],
              [0, 4, 1]], dtype=float)
b = np.array([2, 12, 2], dtype=float)

# 增广矩阵
Ab = np.hstack([A, b.reshape(-1, 1)])

# 消元过程　
# Step 1: R2 = R2 - 3*R1
Ab[1] = Ab[1] - 3 * Ab[0]

# Step 2: R3 = R3 - 2*R2 (after modifying R2)
Ab[2] = Ab[2] - 2 * Ab[1]

# 回带求解
z = Ab[2, 3] / Ab[2, 2]
y = (Ab[1, 3] - Ab[1, 2] * z) / Ab[1, 1]
x = (Ab[0, 3] - Ab[0, 2] * z - Ab[0, 1] * y) / Ab[0, 0]

print(f"解为: x = {x}, y = {y}, z = {z}")

解为: x = 2.0, y = 1.0, z = -2.0


In [14]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 行向量
r = np.array([[1, 2, 7]])  # shape: (1, 3)

# 左乘
result = r @ A  # shape: (1, 3)

print(result)

[[58 68 78]]


$C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}$

我们现在专注解释你想要理解的矩阵乘法为何会产生一个完整的新矩阵，并用生活场景说明它的实际含义和意义。这比点乘更深一层，因为你关心的是：

为什么两个矩阵相乘后，会得到一个新的“整块”矩阵？这块矩阵到底表示了什么？

⸻

🎯 我们的问题是：

给定两个矩阵：
	•	A \in \mathbb{R}^{m \times n}
	•	B \in \mathbb{R}^{n \times p}

为什么 C = A \cdot B \in \mathbb{R}^{m \times p} 是一个新的 m \times p 矩阵？它每一个元素的实际含义是什么？

⸻

🧠 数学解释先导

矩阵乘法定义：

C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}

也就是说：
	•	第 i 行的 整行向量（来自 A）
	•	与第 j 列的 整列向量（来自 B）
	•	做点乘得到结果 C_{ij}

而 A 的每一行 × B 的每一列，都能生成 C 的一个元素 —— 全部跑一遍，自然形成一个新矩阵。

⸻

🏪 现实生活例子：学生考试成绩 × 不同权重 = 多科成绩评价

📋 矩阵 A：每个学生的考试原始成绩

学生 \ 题型	单选	多选	填空	简答
学生1	20	30	25	15
学生2	18	25	30	20
学生3	22	28	27	18

记作矩阵 A \in \mathbb{R}^{3 \times 4}

⸻

📘 矩阵 B：每种题型在各个科目下的权重（例如语文、数学、英语）

题型 \ 科目	语文	数学	英语
单选	0.2	0.3	0.1
多选	0.3	0.4	0.2
填空	0.1	0.2	0.3
简答	0.4	0.1	0.4

记作矩阵 B \in \mathbb{R}^{4 \times 3}

⸻

🔢 矩阵乘积 C = A \cdot B \in \mathbb{R}^{3 \times 3}

得到一个新矩阵 C，形状是 3 \times 3：

学生 \ 科目	语文	数学	英语
学生1	？	？	？
学生2	？	？	？
学生3	？	？	？

每一个 C_{ij} 是：学生 i 的作答情况 × 每题型对科目 j 的权重 → 得到该学生在该科目的总分

⸻

✅ 矩阵乘法生成新矩阵的意义

原始矩阵的含义	矩阵乘法操作	新矩阵的意义
每行 = 一个“样本”	对每个样本逐个点乘目标矩阵的列向量	每个样本对多个“维度”的新投影
每列 = 不同维度/指标	行向量 × 列向量 → 产生新指标/综合评价	形成一个完整的新数据结构（如得分矩阵）


⸻

🧠 更高层次理解：线性映射

矩阵乘法实际上是一个线性变换，你可以把 A \cdot B 理解为：

“把原始空间 A 中的每一行向量，映射到新的坐标系统，由 B 的列决定。”

这个“新的坐标系统”形成了一个新的数据矩阵，每一个维度都可以理解成“压缩、组合、变换”后的综合评价或投影。

⸻

📘 英文总结表达

“Matrix multiplication produces a new matrix where each entry represents the dot product between a row from the first matrix and a column from the second. Conceptually, it’s applying multiple weighted combinations (or linear transformations) across samples and dimensions, generating a new structured dataset.”

⸻

如果你还希望，我可以配一个对应的 Python 代码实现或生成这整个例子的可视化图。要不要试试？