# Elimination with Matrices
视频链接：https://www.youtube.com/watch?v=QVKj3LADCnA

将我的笔记用md/latex公式化、numpy代码化、和plt可视化。要求用到的函数和库都需要给出使用方法的注释

两组矩阵相互点乘，一定把左边那个视为行向量，右边的视为列向量，假设左边的向量a行b列，右边的是c行d列。要使得点乘成立（有意义），必须有b=c，并且输入维度是列数（a行数据b维特征），输出维度是行数。乘积 $A \cdot B 就是一个 a \times d$ 的矩阵。

- 经典意义上的点积:   
$1 \times n 行向量 \cdot n \times 1 列向量 → 标量（scalar）$
比如我们常讲列向量作为一个权重向量。  

- 矩阵乘法（Matrix Multiplication）——是点积的推广:  
$$
	A \in \mathbb{R}^{a \times b} 是一个矩阵\\
	B \in \mathbb{R}^{b \times d} 是另一个矩阵
$$
每一个结果中的元素，就是第 i 行向量 与 第 j 列向量 的点乘结果。

点乘仅产生一个标量，矩阵乘法则会产生一整个新矩阵

In [12]:
import numpy as np

# 初始矩阵
A = np.array([
    [1, 2, 1],
    [3, 8, 1],
    [0, 4, 1]
], dtype=float)

# 第一步：R2 = R2 - 3 * R1
A[1] = A[1] - 3 * A[0]

# 第二步：R3 = R3 - 2 * R2
A[2] = A[2] - 2 * A[1]

print("消元后的矩阵：\n", A)

消元后的矩阵：
 [[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]]


📘 回带求解

💡 原始线性方程组

$$
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1 \\
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z \\
\end{bmatrix}
=
\begin{bmatrix}
2 \\
12 \\
2 \\
\end{bmatrix}
$$

🧮 增广矩阵构造

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
3 & 8 & 1 & 12 \\
0 & 4 & 1 & 2 \\
\end{array}
\right]
$$

🔁 消元过程（带右端向量）
1.	$R_2 \leftarrow R_2 - 3 \times R_1$：

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
0 & 2 & -2 & 6 \\
0 & 4 & 1 & 2 \\
\end{array}
\right]
$$

2.	$R_3 \leftarrow R_3 - 2 \times R_2$：

$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
0 & 2 & -2 & 6 \\
0 & 0 & 5 & -10 \\
\end{array}
\right]
$$

⸻

🔁 回代求解：

由上三角矩阵得到：

$$
\begin{cases}
5z = -10 \Rightarrow z = -2 \\
2y - 2z = 6 \Rightarrow 2y + 4 = 6 \Rightarrow y = 1 \\
x + 2y + z = 2 \Rightarrow x + 2 -2 = 2 \Rightarrow x = 2 \\
\end{cases}
$$

In [13]:
import numpy as np

# 系数矩阵 A 和右端项 b
A = np.array([[1, 2, 1],
              [3, 8, 1],
              [0, 4, 1]], dtype=float)
b = np.array([2, 12, 2], dtype=float)

# 增广矩阵
Ab = np.hstack([A, b.reshape(-1, 1)])

# 消元过程　
# Step 1: R2 = R2 - 3*R1
Ab[1] = Ab[1] - 3 * Ab[0]

# Step 2: R3 = R3 - 2*R2 (after modifying R2)
Ab[2] = Ab[2] - 2 * Ab[1]

# 回带求解
z = Ab[2, 3] / Ab[2, 2]
y = (Ab[1, 3] - Ab[1, 2] * z) / Ab[1, 1]
x = (Ab[0, 3] - Ab[0, 2] * z - Ab[0, 1] * y) / Ab[0, 0]

print(f"解为: x = {x}, y = {y}, z = {z}")

解为: x = 2.0, y = 1.0, z = -2.0


In [14]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 行向量
r = np.array([[1, 2, 7]])  # shape: (1, 3)

# 左乘
result = r @ A  # shape: (1, 3)

print(result)

[[58 68 78]]


$C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}$

## 消元矩阵
## 行交换矩阵与逆矩阵